name: Deploy Site

on:
  workflow_dispatch:

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install graphicsmagick
        run: |
          sudo apt-get update
          sudo apt-get install -y graphicsmagick
      - name: Install Node Dependencies
        run: yarn install --frozen-lockfile
      - name: Deploy Site to GH Pages
        run: |
          git config user.email "simonjwiles@gmail.com"
          git config user.name "Simon Wiles"
          yarn gh-deploy
